/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.omegat;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        String s = "hello";
        assertNotNull("app should have a greeting", s);
    }
}
